### ISSUE TITLE
Resume crash

### ISSUE THREAD

**Issue by elman22** [elman22/pocket-amc-reader#12]
`01-16 16:02:56.020 E/AndroidRuntime(22790): Process: com.holdingscythe.pocketamcreader, PID: 22790
01-16 16:02:56.020 E/AndroidRuntime(22790): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.holdingscythe.pocketamcreader/com.holdingscythe.pocketamcreader.MovieDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.getCount()' on a null object reference
01-16 16:02:56.020 E/AndroidRuntime(22790): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.getCount()' on a null object reference
01-16 16:02:56.020 E/AndroidRuntime(22790):     at com.holdingscythe.pocketamcreader.MovieDetailFragmentHost$MovieDetailAdapter.getCount(MovieDetailFragmentHost.java:70)
01-16 16:02:56.020 E/AndroidRuntime(22790):     at com.holdingscythe.pocketamcreader.MovieDetailFragmentHost.onCreateView(MovieDetailFragmentHost.java:44)
01-16 16:02:56.090 E/ActivityManager(1102): App crashed! Process: com.holdingscythe.pocketamcreader`

**Comment by elman22** [comment]
Fixed
