### ISSUE TITLE
Resume crash #2

### ISSUE THREAD

**Issue by elman22** [elman22/pocket-amc-reader#13]
`01-16 16:03:22.980 E/AndroidRuntime(23116): Process: com.holdingscythe.pocketamcreader, PID: 23116
01-16 16:03:22.980 E/AndroidRuntime(23116): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.holdingscythe.pocketamcreader/com.holdingscythe.pocketamcreader.MovieListActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
01-16 16:03:22.980 E/AndroidRuntime(23116):     at com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.loadConfiguration(MoviesAdapter.java:230)
01-16 16:03:22.980 E/AndroidRuntime(23116):     at com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.<init>(MoviesAdapter.java:56)
01-16 16:03:22.980 E/AndroidRuntime(23116):     at com.holdingscythe.pocketamcreader.MovieListFragment.onActivityCreated(MovieListFragment.java:194)
01-16 16:03:22.980 E/ActivityManager(1102): App crashed! Process: com.holdingscythe.pocketamcreader`

**Comment by elman22** [comment]
Fixed in 2.0-alpha3
