### ISSUE TITLE
Resume crash #3

### ISSUE THREAD

**Issue by elman22** [elman22/pocket-amc-reader#17]
> 04-24 17:14:27.423 E/AndroidRuntime(16965): Process: com.holdingscythe.pocketamcreader, PID: 16965
> 04-24 17:14:27.423 E/AndroidRuntime(16965): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.holdingscythe.pocketamcreader/com.holdingscythe.pocketamcreader.MovieListActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.getBoolean(java.lang.String, boolean)' on a null object reference
> 04-24 17:14:27.423 E/AndroidRuntime(16965):     at com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.loadConfiguration(MoviesAdapter.java:230)
> 04-24 17:14:27.423 E/AndroidRuntime(16965):     at com.holdingscythe.pocketamcreader.catalog.MoviesAdapter.<init>(MoviesAdapter.java:56)
> 04-24 17:14:27.423 E/AndroidRuntime(16965):     at com.holdingscythe.pocketamcreader.MovieListFragment.onActivityCreated(MovieListFragment.java:194)
> 04-24 17:14:27.483 E/ActivityManager(1103): App crashed! Process: com.holdingscythe.pocketamcreader
> 04-24 17:14:27.483 W/ActivityManager(1103):   Force finishing activity com.holdingscythe.pocketamcreader/.MovieListActivity

**Comment by elman22** [comment]
Fixed in 2.0-alpha3
